query Category {
  category {
    getAllCategory {
      ... on CategoryGetAllOk {
        category {
          id
        }
      }
      ... on InternalErrorProblem {
        message
      }
    }
  }
}