query allCategory {
   category {
      getAllCategory {
         __typename
         ... on CategoryGetAllOk {
            category {
               id
               title
               slug
            }
         }
         ... on InternalErrorProblem {
            message
         }
      }
   }
}

mutation AddCategory($input: CreateCategoryInput) {
   category {
      createCategory(input: $input) {
         __typename
         ... on CategoryCreateOk {
            id
         }
         ... on InternalErrorProblem {
            message
         }
         ... on UnauthorizedProblem {
            message
         }
      }
   }
}
