query allCategory {
  category {
    getAllCategory {
      __typename
      ... on CategoryGetAllOk {
        category {
          id
          title
          slug
        }
      }
      ... on InternalErrorProblem {
        message
      }
    }
  }
}